#! /bin/bash
##############################################################################
# Title      :  sam (System Administration Manager)
# Version    :  1.0
# Author     :  Jacques Duplessis
# Date       :  2016-08-25
# Requires   :  bash shell
# SCCS-Id.   :  @(#) sam 3.0 25-Aug-2016
#
##############################################################################
#
# Description
#   This is the Main Program - Display Menu and Load sam.init function script
#       - It load in memory all functions used by sam.
#
##############################################################################
# History    :
#   1.0      Initial Version - Jan 2006 - Jacques Duplessis
#   1.2b     Change function lxexist - if lvname exist in /etc/fstab 
#   3.0      Jacques - Aug 2016  - Updated for RHEL7 xfs filesystem
#
##############################################################################





##############################################################################
# Display Menu Principal
##############################################################################
display_main_menu()
{
	display_entete "System Administration Menu" 
	writexy 05 15 "1- Filesystem tools........................"
    writexy 07 15 "2- Create system group on Linux farm......."
    writexy 09 15 "3- Global Filesystem Tools................."
    writexy 11 15 "4- RPM DataBase Tools......................"
	writexy 14 15 "Q- Quit S.A.M.............................."
    writexy 21 29 "${rvs}Option ? ${nrm}_${right}"
	writexy 21 38 " "
}



##############################################################################
# Verify If environement variable "san" is defined
##############################################################################
verify_env()
{
if [ "$SAM" = "" ]
   then
   tput clear
   echo -e "Please define the \"SAM\" environment variable"
   echo -e "It got to point the \"sam\" directory"
   echo -e "---"
   echo -e "Press [ENTER]"
   read dummy
   exit 1
   fi


# Test if "san" environment variable direct to the proper directory
if [ ! -f "$SAM/sam" ]
   then
   tput clear
   echo -e "The script \"sam\" is not in $SAM directory"
   echo -e "It got to point the \"sam\" directory"
   echo -e "---"
   echo -e "Press [ENTER]"
   read dummy
   exit 1
   fi
}






##############################################################################
#    M A I N      S E C T I O N   -   P R O G R A M   S T A R T    H E R E 
##############################################################################
#
stty_orig=`stty -g`                 # Save stty setting    
#stty erase "^H"                      # Make sure backspace work as expected
CURDIR=`pwd` ; export CURDIR		# Save Current Directory
SAM=/sadmin/sam
verify_env				            # Verify if SAM env. var. is defined
cd $SAM					            # Change to manager directory
. $SAM/sam.init				        # Load Function used by SAM
StripFile "$SAMLOG"             	# Keep last 5000 rec. of SAM Log file


# Display Menu and Process request
while :
	do
	display_main_menu
	read REPONSE
	case $REPONSE in
        1) # FILESYSTEMS
           if [ $CLUSTER = "Y" ]
              then messok 22 01 "In a cluster, we use GFS not ext[3-4] (unless on rootvg), Continue "
                   if [ "$?" = "1" ] ; then . $SAM/sam_fs.sh ; fi
              else . $SAM/sam_fs.sh 
           fi 
           ;;

		2) # Create Group 
	   	   . $SAM/sam_create_group.sh
           ;;

		3) # Global Filesystem Tools
           if [ $CLUSTER = "N" ]
              then mess "Option only available when run within a cluster."
              else . $SAM/sam_gfs.sh
           fi 
           ;;

		4) # RPM Tools
	   	   . $SAM/sam_rpm_tools.sh
           ;;

   Q | q ) # QUITTER #
           stty $stty_orig
           cd $CURDIR
	       exit 0
	       ;;
        *) # OPTION INVALIDE #
		   mess "Invalid option - $REPONSE"
           ;;
	esac
done

