#!/bin/ksh
#----------------------------------------------------------------------------- 
# Script   : sam_exfsauto - Re-size Logical Volume in background mode
# Version  : 1.0.0
# Auteur   : Marc Giguere 
# Date     : Wed Dec 29 16:38:19 EST 2004
#----------------------------------------------------------------------------- 
# sam_exfsauto <Tagname>
# file autoextendfs.dat format
# tagname:lvname:extend_size  (in megs)
#----------------------------------------------------------------------------- 
export PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin
export PROGRAM_NAME=sam_exfsauto
export SAMDIR=/sysadmin/sam
export EXFSFILE=$SAMDIR/sam_exfsauto.dat
export LOGFILE=sam.log

#----------------------------------------------------------------------------- 
# fonction : do_log
#----------------------------------------------------------------------------- 
do_log()
{
  message="$1"
  dt=`date +"%Y%m%d %H:%M:%S"`
  echo "$dt - $PROGRAM_NAME : $message" >> $LOGFILE
}

#----------------------------------------------------------------------------- 
# fonction : do_usage
#----------------------------------------------------------------------------- 
do_usage()
{
   echo "Usage: sam_exfsauto <Tagname>"
   exit 1
}

#----------------------------------------------------------------------------- 
# fonction : do_clean_tag
#----------------------------------------------------------------------------- 
do_clean_tag()
{
  TG="$1"
  do_log "Clean tag entry in $EXFSFILE"
  nawk 'BEGIN{FS=":"}
        { if ($1==TAG){next}
          print $0 }
       ' TAG=$TG $EXFSFILE > $EXFSFILE.tmp
  cp $EXFSFILE $EXFSFILE.last
  mv $EXFSFILE.tmp $EXFSFILE
}

#----------------------------------------------------------------------------- 
# Main
#----------------------------------------------------------------------------- 

if [ $# -ne 1 ]
   then do_usage
fi

TAGNAME="$1"

#-- autoextendfs.dat exist ???
if [ ! -a $EXFSFILE ]
   then do_log "Error - $EXFSFILE file not found"
        exit 1
fi

do_log "Start TAG=$TAGNAME"
for LINE in `nawk 'BEGIN{FS=":"}{if ($1==TAG){print $0}}' TAG=$TAGNAME $EXFSFILE`
do
   
   LVNAME=`echo $LINE|nawk 'BEGIN{FS=":"}{print $2}'`
   LVSIZE=`echo $LINE|nawk 'BEGIN{FS=":"}{print $3}'`

   echo "$SAMDIR/sam_exfs $LVSIZE $LVNAME"
   $SAMDIR/sam_exfs $LVSIZE $LVNAME
   RTN_CODE=$?
   if [ "$RTN_CODE" = 0 ]
      then do_log "extend LV $LVNAME Size=$LVSIZE"
      else do_log "Error - extend LV $LVNAME Size=$LVSIZE"
   fi

done

do_clean_tag $TAGNAME

do_log "Finish TAG=$TAGNAME"
exit 0
